.Dd October 16, 2013
.Dt DF 1 1
.Os Linux
.Sh NAME
.Nm df
.Nd show file system usage
.Sh SYNOPSIS
.Nm df
.Op Fl ahis
.Sh DESCRIPTION
df displays the amount of disk space available on a file system.
.Pp
If no arguments are given, df shows all the file systems using 512-byte
blocks.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
Show all file systems including dummy ones.
.It Fl h
Not implemented.
.It Fl s
Not implemented.
.It Fl i
Not implemented.
.El
