.TH DF 1 ubase\-VERSION
.OS Linux
.SH NAME
df \- show file system usage
.SH SYNOPSIS
.B df
.RB [ \-ahsi ]
.SH DESCRIPTION
df displays the amount of disk space available on a file system.
If no arguments are given, df shows all the file systems using 512-byte
blocks.
.SH OPTIONS
.TP
.BI \-a
Show all file systems including dummy ones.
.TP
.BI \-h
Not implemented.
.TP
.BI \-s
Not implemented.
.TP
.BI \-i
Not implemented.
