.TH DF 1 ubase-VERSION
.SH NAME
\fBdf\fR - Show file system usage
.SH SYNOPSIS
\fBdf\fR [\fB-ahsi\fR]
.SH DESCRIPTION
\fBdf\fR displays the amount of disk space available on a file system.
If no arguments are given, df shows all the file systems using 512-byte
blocks.
.SH OPTIONS
.TP
\fB-a\fR
Show all file systems including dummy ones. This is the default
option.
.TP
\fB-h\fR
Not implemented.
.TP
\fB-s\fR
Not implemented.
.TP
\fB-i\fR
Not implemented.
