.Dd October 16, 2013
.Dt EJECT 1 1
.Os Linux
.Sh NAME
.Nm eject
.Nd eject removable media
.Sh SYNOPSIS
.Nm eject
.Op Fl t
.Sh DESCRIPTION
eject allows the CD-ROM tray to be opened or closed under software
.br
control.
.Pp
If no arguments are given, the CD-ROM tray is opened.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl t
If supported, close the CD-ROM tray.
.El
