.TH EJECT 1 ubase-VERSION
.SH NAME
\fBeject\fR - Eject removable media
.SH SYNOPSIS
\fBeject\fR [\fB-t\fR]
.SH DESCRIPTION
\fBeject\fR allows the CD-ROM tray to be opened or closed under software
control.  If no arguments are given, the CD-ROM tray is opened.
.SH OPTIONS
.TP
\fB-t\fR If supported, close the CD-ROM tray.
