.Dd February 2, 2015
.Dt EJECT 1
.Os ubase
.Sh NAME
.Nm eject
.Nd eject removable media
.Sh SYNOPSIS
.Nm
.Op Fl t
.Sh DESCRIPTION
.Nm
allows the CD-ROM tray to be opened or closed under software
control. If no arguments are given, the CD-ROM tray is opened.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl t
If supported, close the CD-ROM tray.
.El
