.TH FALLOCATE 1 ubase-VERSION
.SH NAME
\fBfallocate\fR - Preallocate blocks to a file
.SH SYNOPSIS
\fBfallocate\fR [\fB-o\fI offset\fR] \fB-l\fR \fIlength file\fR
.SH DESCRIPTION
\fBfallocate\fR preallocates blocks to a file.  Only certain filesystems
support the fallocate system call.  This is a very fast operation to allocate
uninitialized blocks in a file without doing any IO.
As  of the Linux kernel v2.6.31, the fallocate system call is supported
by the btrfs, ext4, ocfs2, and xfs filesystems.
.SH OPTIONS
.TP
\fB-o\fR
Specifies the beginning offset of the allocation, in bytes.
.TP
\fB-l\fR
Specifies the length of the allocation, in bytes.
.SH SEE ALSO
fallocate(2)
