.TH FREE 1 ubase-VERSION
.SH NAME
\fBfree\fR - Display amount of free and used memory in the system
.SH SYNOPSIS
\fBfree\fR [\fB-bkmg\fR]
.SH DESCRIPTION
\fBfree\fR displays the total amount of free and used physical and swap
memory in the system, as well as the buffers used by the kernel.
.SH OPTIONS
.TP
\fB-b\fR
Display the amount of memory in bytes.  This is the default.
.TP
\fB-k\fR
Display the amount of memory in kilobytes.
.TP
\fB-m\fR
Display the amount of memory in megabytes.
.TP
\fB-g\fR
Display the amount of memory in gigabytes.
