.TH HALT 8 ubase-VERSION
.SH NAME
\fBhalt\fR - Power-off or reboot the machine
.SH SYNOPSIS
\fBhalt\fR [\fB-pr\fR]
.SH DESCRIPTION
\fBhalt\fR can be used to power-off or reboot the machine.
This is a low-level tool and should not be used directly or data-loss
can happen if the filesystems are not properly unmounted first.
.SH OPTIONS
.TP
\fB-p\fR Power-off the machine.
.TP
\fB-r\fR Reboot the machine.
