.Dd October 17, 2013
.Dt HALT 8 1
.Os Linux
.Sh NAME
.Nm halt
.Nd Halt, power-off or reboot the machine
.Sh SYNOPSIS
.Nm halt
.Op Fl pr
.Sh DESCRIPTION
halt can be used to halt, power-off or reboot the machine.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl p
power-off the machine.
.It Fl r
reboot the machine.
.El
