.TH INSMOD 8 ubase-VERSION
.SH NAME
\fBinsmod\fR - Insert a module into the Linux kernel
.SH SYNOPSIS
\fBinsmod\fR \fIfilename\fR [\fIargs...\fR]
.SH DESCRIPTION
\fBinsmod\fR inserts the module specified by \fIfilename\fR
into the kernel.  It does not handle module dependencies.
.SH SEE ALSO
rmmod(8), lsmod(8)
