.TH LASTLOG 8 ubase-VERSION
.SH NAME
\fBlastlog\fR - Show last login of users
.SH SYPNOSIS
\fBlastlog\fI [user ...]
.SH DESCRIPTION
\fBlastlog\fR Show time, tty, and host (if it was a remote
connection) of last login of users. If some user names are passed
as parameter then information about last login of these users is
shown, otherwise is shown for all the users in /etc/passwd in the
order they appear in it.
