.TH LOGIN 1 ubase-VERSION
.SH NAME
\fBlogin\fR - Log into the system
.SH SYNOPSIS
\fBlogin\fR [\fB-p\fR] \fIusername\fR
.SH DESCRIPTION
\fBlogin\fR logs the \fIusername\fR into the system.  It sets \fBHOME\fR,
\fBSHELL\fR, \fBUSER\fR, \fBLOGNAME\fR, \fBTERM\fR and the \fBPATH\fR environment
variables and invokes the login shell as specified in \fI/etc/passwd\fR.
.SH OPTIONS
.TP
\fB-p\fR
Preserve the environment.
