.TH MKNOD 1 ubase-VERSION
.SH NAME
\fBmknod\fR - create a special device file
.SH SYNOPSIS
\fBmknod\fR [\fB-m \fImode\fR] \fIname type major minor
.SH DESCRIPTION
\fBmknod\fR reates a special device file named \fIname\fR
with major number \fImajor\fR, and minor number \fIminor\fR.
\fItype\fR specifies what kind of special file will be created
and must be one of:
.TP
\fBu\fR or \fBc\fR A character device.
.TP
\fBb\fR
A block device.
.SH OPTIONS
.TP
\fB-m\fR \fImode\fR
Set the mode of the new file based on the octal value of
\fImode\fR.
.SH SEE ALSO
mknod (2)
