.TH MKSWAP 8 ubase-VERSION
.SH NAME
\fBmkswap\fR - Set up a Linux swap area
.SH SYNOPSIS
\fBmkswap\fR \fIdevice\fR
.SH DESCRIPTION
\fBmkswap\fR sets up a Linux swap area on a device or in a file.  The
\fIdevice\fR argument will usually be a disk-partition but it can also be a
file.  After creating the swap area you will typically need to use the
\fBswapon\fR command to start using it.
.SH SEE ALSO
swapon(8)
