.TH PASSWD 1 ubase-VERSION
.SH NAME
\fBpasswd\fR - Change a user's password
.SH SYNOPSIS
\fBpasswd\fR [\fIusername\fR]
.SH DESCRIPTION
\fBpasswd\fR changes the user's password. The user is prompted
for their current password.  If the current password is correctly typed,
a new password is requested.  The new password must be entered twice to
avoid typing errors.  The superuser is not required to provide a user's
current password.
