.TH PIVOT_ROOT 8 ubase-VERSION
.SH NAME
\fBpivot_root\fR - change the root filesystem
.SH SYNOPSIS
\fBpivot_root\fI new_root put_old\fR
.SH DESCRIPTION
\fBpivot_root\fR moves the root file system of the current process to the
directory \fIput_old\fR and makes \fInew_root\fR the new root file system.
