.TH READAHEAD 8 ubase-VERSION
.SH NAME
\fBreadahead\fR - Preload files into disk cache
.SH SYNOPSIS
\fBreadahead\fR \fIfile...\fR
.SH DESCRIPTION
\fBreadahead\fR preloads files into the kernel's disk cache.  The
number of pages preloaded depends on the kernel but it is usually around
2MB.
.SH SEE ALSO
readahead(2)
