.TH RESPAWN 1 ubase-VERSION
.SH NAME
\fBrespawn\fR - Spawn the given command repeatedly
.SH SYNOPSIS
\fBrespawn\fR [\fB-d\fI N\fR] \fIcmd\fR [\fIargs...\fR]
.SH DESCRIPTION
\fBrespawn\fR spawns the given \fIcmd\fR in a new session
repeatedly.
.SH OPTIONS
.TP
\fB-d\fR
Set the delay between invocations of \fIcmd\fR.  It defaults to 0.
