.TH SWAPOFF 8 ubase-VERSION
.SH NAME
\fBswapoff\fR - disable devices and files for paging and swapping
.SH SYNOPSIS
\fBswapoff\fR [\fB-a\fI device\fR]
.SH DESCRIPTION
\fBswapoff\fR disables swapping on the specified devices and files.
.SH OPTIONS
.TP
\fB-a\fR
Disable swapping on all known swap devices and files as found in /etc/fstab.
