.TH UNSHARE 1 ubase-VERSION
.SH NAME
\fBunshare\fR - run program with some namespaces unshared from parent
.SH SYNOPSIS
\fBunshare\fR [\fB-muinpU\fR] cmd [\fIargs...\fR]
.SH DESCRIPTION
\fBunshare\fR
Unshares the indicated namespaces from the parent process
and then executes the specified program. The namespaces to be unshared are
indicated via options.
.SH OPTIONS
.TP
\fB-m\fR
Unshare the mount namespace, so that the calling process has a private
copy of its namespace which is not shared with any other process.
This flag has the same effect as the \fBclone(2) CLONE_NEWNS\fR flag.
.TP
\fB-u\fR
Unshare the UTS IPC namespace, so that the calling process has a
private copy of the UTS namespace which is not shared with any other
process. This flag has the same effect as the \fBclone(2) CLONE_NEWUTS\fR
flag.
.TP
\fB-i\fR
Unshare the System V IPC namespace, so that the calling process has a
private copy of the System V IPC namespace which is not shared with
any other process. This flag has the same effect as the \fBclone(2)
CLONE_NEWIPC\fR flag
.TP
\fB-n\fR
Unshare the network namespace, so that the calling process is moved
into a new network namespace which is not shared with any previously
existing process. This flag has the same effect as the \fBclone(2)
CLONE_NEWNET\fR flag.
.TP
\fB-p\fR
Create the process in a new PID namespace. This flag has the same
effect as the \fBclone(2) CLONE_NEWPID\fR flag.
.TP
\fB-U\fR
The process will have a distinct set of UIDs, GIDs and capabilities.
.SH SEE ALSO
clone(2), unshare(2)
