.TH UPTIME 1 ubase-VERSION
.SH NAME
\fBuptime\fR - Tell how long the system has been running.
.SH SYNOPSIS
\fBuptime\fR
.SH DESCRIPTION
\fBuptime\fR gives a one line display of the following information.
The current time, how long the system has been running, how many users are
currently logged on and the system load averages for the past 1, 5 and
15 minutes.
.SH SEE ALSO
ps(1), utmp(5)
