.TH WHO 1 ubase-VERSION
.SH NAME
\fBwho\fR - Print who has logged on
.SH SYNOPSIS
\fBwho\fR [\fB-m\fR]
.SH DESCRIPTION
\fBwho\fR prints a list of who has logged on, their controlling tty, and the
time at which they logged on.
.SH OPTIONS
.TP
\fB-m\fR
Only show users on current tty.
.TP
\fB-l\fR
Print LOGIN processes as well.
.SH BUGS
\fBwho\fR relies on the utmp file to be updated responsibly. This
doesn't always happen, which can cause who to print completely
bogus data.
.SH SEE ALSO
utmp(5)
